# -*- coding: utf-8 -*-
"""imagenet_pretraining

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GrQH7IwbGO2FMHvu_W1T2MLj7yfhJazl

### 1. Environment Setup
Install the necessary libraries for downloading the file and running Vision Transformer models.
"""

!pip install gdown transformers datasets accelerate evaluate

"""### 2. Download and Extract the Project
Download the compressed project file from Google Drive and extract it to inspect its contents.
"""

import gdown
import os

# Download the file using the provided Google Drive ID
file_id = '1ZPyOGPy5coUiDJ5UyrojGr7NLb0MwJ0J'
output_path = 'vit_project.zip'

if not os.path.exists(output_path):
    # Try using the 'id' parameter directly which is more reliable for gdown
    gdown.download(id=file_id, output=output_path, quiet=False)

# Extract the contents
!unzip -q -o vit_project.zip -d vit_project_files

# List the extracted files to understand the project structure
!ls -R vit_project_files

"""### 3. ImageNet Dataset Preparation
Downloading the full ImageNet dataset requires authentication. You can use Hugging Face's `datasets` library to manage it easily. *Note: You will need to use your Hugging Face token to access `imagenet-1k`.*
"""

from getpass import getpass

from huggingface_hub import login

# Run this to log in to Hugging Face and access the dataset
hf_token = getpass("Paste your Hugging Face token: ").strip()
login(token=hf_token)

from datasets import load_dataset

# Load the dataset (Uncomment after logging in and accepting terms on Hugging Face)
# dataset = load_dataset("imagenet-1k", split="train")
# print(dataset)

"""### 4. Load Pre-trained ViT Weights
We will use Hugging Face `transformers` to load the pre-trained ViT model and prepare it for continued pre-training or fine-tuning.
"""

from transformers import AutoImageProcessor, AutoModelForImageClassification

model_name = "google/vit-base-patch16-224"

# Load the image processor to correctly format images for ViT
processor = AutoImageProcessor.from_pretrained(model_name)

# Load the pre-trained ViT model
model = AutoModelForImageClassification.from_pretrained(model_name)

print("Model and processor loaded successfully. Ready to continue training!")

"""### 5. Install Project Dependencies
The README specifies a few more required libraries for this specific project, such as `timm` for the ViT models and `einops` for tensor operations.
"""

!pip install einops timm scipy tensorboard diffusers google-api-python-client google-auth kaggle

"""### 6. Prepare ImageNet Directory Structure
The project expects the data at `data/imagenet/train/` and `data/imagenet/val/` with subfolders for each class.

*Warning: The full ImageNet-1k dataset is ~150GB. Standard Colab instances only have ~80-100GB of disk space. The script below exports a tiny subset for testing. To download the full dataset, remove the `select(range(100))` part, but you will need Colab Pro with extended disk space or mount Google Drive.*
"""

import os
from datasets import load_dataset
from PIL import Image
from tqdm import tqdm
import numpy as np

# Create directory structure
data_root = '/content/data/imagenet'
os.makedirs(f'{data_root}/train', exist_ok=True)
os.makedirs(f'{data_root}/val', exist_ok=True)

print("Attempting to load dataset from Hugging Face...")
try:
    # Load dataset (Requires Hugging Face login and accepting terms on the dataset page)
    # Make sure you visit https://huggingface.co/datasets/imagenet-1k and accept the terms!
    dataset_train = load_dataset("imagenet-1k", split="train")
    dataset_val = load_dataset("imagenet-1k", split="validation")

    # Using a small subset for testing
    dataset_train_subset = dataset_train.select(range(100))
    dataset_val_subset = dataset_val.select(range(100))

    def save_split(dataset_split, split_name):
        print(f"Saving {split_name} images...")
        for i, item in enumerate(tqdm(dataset_split)):
            img = item['image']
            label = item['label']

            class_dir = os.path.join(data_root, split_name, str(label))
            os.makedirs(class_dir, exist_ok=True)

            if img.mode != 'RGB':
                img = img.convert('RGB')
            img.save(os.path.join(class_dir, f'{i}.jpg'))

    save_split(dataset_train_subset, 'train')
    save_split(dataset_val_subset, 'val')
    print("Real dataset preparation complete!")

except Exception as e:
    print(f"Error loading real dataset: {e}")
    print("Generating dummy images for testing so the training script can run...")

    for split in ['train', 'val']:
        for class_id in range(5):  # 5 classes
            class_dir = os.path.join(data_root, split, str(class_id))
            os.makedirs(class_dir, exist_ok=True)
            for img_id in range(10):  # 10 images per class
                dummy_img = Image.fromarray(np.random.randint(0, 255, (224, 224, 3), dtype=np.uint8))
                dummy_img.save(os.path.join(class_dir, f'{img_id}.jpg'))

    print("Dummy dataset preparation complete! You can now test the training script.")

"""### 7. Run Pre-Training
Run the `train_ssl_freq_mae.py` script. According to the `README`, passing `--timm_model_name vit_base_patch16_224.mae` and `--timm_pretrained` will automatically download and load the required ViT weights.

*Note: We use `nproc_per_node=1` because standard Colab only has 1 GPU, and reduced the batch size to fit in Colab GPU memory.*
"""

import os
os.chdir('/content/vit_project_files/imagenet-ssl-main')

!torchrun --standalone --nnodes=1 --nproc_per_node=1 train_ssl_freq_mae.py \
  --dataset imagenet \
  --data_root /content/data/imagenet \
  --train_dir /content/data/imagenet/train \
  --val_dir /content/data/imagenet/val \
  --output_dir /content/logs/imagenet/ssl_freq_mae \
  --experiment mr075 \
  --epochs 10 \
  --batch_size 32 \
  --val_batch_size 32 \
  --num_workers 2 \
  --grad_accum_steps 4 \
  --base_lr 1.5e-4 \
  --image_size 224 \
  --block_size 16 \
  --patch_size 16 \
  --mask_ratio 0.75 \
  --timm_model_name vit_base_patch16_224.mae \
  --timm_pretrained \
  --amp
